# Generated by Django 3.2.4 on 2022-08-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../k08ldncqhxfo8hbef3el', upload_to='images/'),
        ),
    ]
